### ISSUE TITLE
Inline web worker

### ISSUE THREAD

**Issue by NicolasRannou** [andywer/threads-plugin#18]
Hi,

Is there any option to inline web workers?

Can't seem to find how to do so anywhere.

Thanks for the awesome library!

**Comment by andywer** [comment]
Right now this is not possible, but there is a discussion about it at andywer/threads.js#211. It's not overly active right now, but you are of course welcome to participate! 🙂

**Comment by NicolasRannou** [comment]
Thank you I'll investigate it a little bit more.

I'd like to develop a JS library that leverages web-workers and I must ensure it is easy to serve it or for customers to use (i.e. no worker-specific setup) if the web worker is not inlined!
