### ISSUE TITLE
Failed to build a worker with zstd-codec module if no {target: "node"} provided

### ISSUE THREAD

**Issue by EvgenyRodygin** [andywer/threads-plugin#23]
Hi again Andy,

I have another issue which I have already somehow overcome.
The resolution is at the bottom of this post though it seems to be not the best one.

ThreadsPlugin refuses to build a worker utilizing [zstd-codec](https://github.com/yoshihitoh/zstd-codec) module.
I've created a sample [repository](https://github.com/EvgenyRodygin/zstd-worker-test) for this issue.
I duplicate the files in case it gets someday unavailable.
- index.js:
```js
import {Worker} from "threads"
const worker = new Worker("./zstd_worker.js");
```
- zstd_worker.js
```js
import zstd from "zstd-codec";
```
- webpack.config.js:
```js
const path = require("path");
const ThreadsPlugin = require('threads-plugin');

module.exports = {

  target: "node",

  mode: "development",

  module: {
    rules: [
      {
        test: /\.(js)$/,
        exclude: /node_modules/,
        use: "babel-loader"
      }
    ]
  },

  entry: "./index.js",

  plugins: [
    new ThreadsPlugin(),
  ],

  externals: { "tiny-worker": "tiny-worker" },

  output: {
    path: path.resolve("build"),
  }

}
```
- babelrc:
```json
{
  "presets": [["@babel/preset-env", {"modules": false}]]
}
```

The solution which works for me is to replace the plugin entry with:
```
new ThreadsPlugin({target: "node"}),
```
Looks a bit dirty. Though if this is an intended behavior I'd be glad to know the reason.

**Comment by andywer** [comment]
I just published `threads-plugin v1.3.3` – it should fix that issue, too 😉
