### ISSUE TITLE
Doesn't work with webpack 5 (`webpack/lib/ParserHelpers` doesn't exist)

### ISSUE THREAD

**Issue by andreialecu** [andywer/threads-plugin#27]
It seems that a private API from `webpack` is being used here: 

https://github.com/andywer/threads-plugin/blob/1a1b070b862c36f060bf81704141e491e1e708f5/src/index.js#L19

This doesn't exist in Webpack 5 any more.

**Comment by andywer** [comment]
Ahh, shit. Thanks for pointing out!

Time to pull updates from the plugin that this is based on. Need to find a bit of time for that as there will likely be a lot of merge conflicts…

**Comment by andreialecu** [comment]
I'll actually be sending a small PR/diff with Webpack 5 support in a few minutes, as a quick band-aid. The file still exists but it was moved elsewhere.

**Comment by andreialecu** [comment]
I opened #28 which inlines the `ParserHelpers`, and only imports something that exists in both 4 and 5.

I'm not able to run the test suite though. Let's continue discussion in #28.

**Comment by bbudd** [comment]
FWIW, it's been renamed to `JavascriptParserHelper`: https://webpack.js.org/blog/2020-10-10-webpack-5-release/

fixed code for this import is [here](https://github.com/GoogleChromeLabs/worker-plugin/blob/master/src/index.js#L19):

```javascript
let ParserHelpers;
try {
  ParserHelpers = require('webpack/lib/javascript/JavascriptParserHelpers'); // Webpack 5
} catch (e) {}
ParserHelpers = ParserHelpers || require('webpack/lib/ParserHelpers'); // Webpack 4
```

I'd put in a PR for just this fix, but there's a few updates beyond this which likely need doing as well. Going to poke around and see if I can get it running locally, if I have time I'll put a PR up


EDIT: PR is up, #33 - I made just the changes from the base repo which targeted webpack 5.
