### ISSUE TITLE
Node.js build, ReferenceError: self is not defined

### ISSUE THREAD

**Issue by kevzettler** [andywer/threads-plugin#30]
Getting the following error from a webpack Node.js build. 

```
ReferenceError: self is not defined
    at Module.../node_modules/ts-loader/index.js?!./server.worker.ts (/Users/kevzettler/code/hypeworks/build/webpack:/server.worker.ts:187:1)
    at __webpack_require__ (/Users/kevzettler/code/hypeworks/build/webpack:/webpack/bootstrap:19:1)
    at /Users/kevzettler/code/hypeworks/build/webpack:/webpack/bootstrap:83:1
    at Object.<anonymous> (/Users/kevzettler/code/hypeworks/build/0.server.worker.js:88:10)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at MessagePort.<anonymous> (internal/main/worker_thread.js:162:24)
```

I have the threads plugin configured like:
```
    new ThreadsPlugin({
      globalObject: 'self'
    })
```

I have a worker file like:

```
self.addEventListener('message', (event) => {
  if(event.data && event.data.type ){
    rootState.dispatch(event.data);
  }else{
    console.warn('unsure what to do with message passed to worker...', event);
  }
});
```

**Comment by andywer** [comment]
Hey Kevin,

there is no such API as `self.addEventListener()` in a node.js worker thread, that's only in web workers and when using the tiny-worker polyfill. Use threads.js' `expose()` instead 😉

If you really want to go low-level, you will have to deal with that x-platform stuff yourself. Maybe it would be worth to make threads.js expose something so that you can subscribe to raw messages more easily.

On the other hand you are kind-of working against the library. Why not `expose()` a dispatch function and call it from the main thread?

**Comment by kevzettler** [comment]
@andywer thanks for responding. Thanks for all your help.

>there is no such API as self.addEventListener() in a node.js worker thread, that's only in web workers and when using the > tiny-worker polyfill. Use threads.js' expose() instead 😉

I was under the impression, from our conversation at https://github.com/andywer/threads.js/issues/311 that I would not need to touch the expose interface. It was my understanding that `threads.js` was a universal (isomorphic) interface for dealing with workers. 

You're saying that I could use `tiny-worker` with `threads.js` ? or just `tiny-worker` alone. Also I am on `node 12+` and the Readme says that does not use `tiny-worker` 

> On the other hand you are kind-of working against the library. Why not expose() a dispatch function and call it from the main thread?

Yes I agree with you. It seems `threads.js` has an interface designed for "delayed job" style threads. That meaning threads that are invoked to run a calculation and return a value over an RPC like interface. 

In my project I am creating a long running thread worker that contains a game loop. The loop runs indefinitely and pumps messages back to the parent thread. This interface doesn't require any RPC style connection and is more of an event or stream based pubsub.

**Comment by andywer** [comment]
> I was under the impression, from our conversation at andywer/threads.js#311 that I would not need to touch the expose interface. It was my understanding that threads.js was a universal (isomorphic) interface for dealing with workers.

Ahh, I see. Well, yes and no. It is for spawning workers and communicating main -> worker, but for worker -> main communication, we provide the `expose()` function only.

>You're saying that I could use tiny-worker with threads.js ? or just tiny-worker alone. Also I am on node 12+ and the Readme says that does not use tiny-worker

Either way tiny-worker will allow you to spawn a worker that works in a very web-worker-like way.

> This interface doesn't require any RPC style connection and is more of an event or stream based pubsub.

Then return an observable from your game loop function and keep emitting data back to the main thread :)

Maybe it would be easier if we supported returning event emitters transparently from workers. But trust me, observables do the same job in a cleaner way 😉

**Comment by kevzettler** [comment]
> Then return an observable from your game loop function and keep emitting data back to the main thread :)

> Maybe it would be easier if we supported returning event emitters transparently from workers. But trust me, observables do the same job in a cleaner way 😉

This makes sense to me. Unfortunately it would take some significant refactoring of the existing code base. Additionally, it would take some research to evaluate if `zen-observable` has the performance capabilities we need and properly handles garbage collection. 

I have noticed that the various implementations of the workers in `src/worker/implementation.*.ts` have functions for `postMessageToMaster` https://github.com/andywer/threads.js/search?q=postMessageToMaster and that the `worker-threads` seems to have `parentPort.postMessage(message);` implemented. It's not clear to me how I would access that from within the worker code is that possible?

let me know your thoughts @andywer

**Comment by andywer** [comment]
`postMessageToMaster()`: No direct way to access them, I think. Internal-only funcions as of now.

> evaluate if zen-observable has the performance capabilities we need and properly handles garbage collection

Fair enough, but as long as there's no memory leak in the observable implementation, it shouldn't make much of a difference. Unless you do a million microscopic iterations per second in your loop, maybe – otherwise the cost of your iteration code should outweigh the overhead of the thing that propagates your events by multiple orders of a magnitude 😉

**Comment by kevzettler** [comment]
> postMessageToMaster(): No direct way to access them, I think. Internal-only funcions as of now.

yes ok I see it would have to be exported from https://github.com/andywer/threads.js/blob/master/src/worker/index.ts which exports the `expose` wrapper

>Fair enough, but as long as there's no memory leak in the observable implementation, it shouldn't make much of a difference. Unless you do a million microscopic iterations per second in your loop, maybe – otherwise the cost of your iteration code should outweigh the overhead of the thing that propagates your events by multiple orders of a magnitude 😉

Yes we are doing crazy stuff like this to maintain 60fps and can't risk any unknown overhead. Thank you for your help @andywer you've given me lots to consider
