### ISSUE TITLE
"No instantiations" after upgrading to Webpack@5 & Electron@11

### ISSUE THREAD

**Issue by Nantris** [andywer/threads-plugin#37]
This issue occurs in development. I've not tested production yet.

I've tried making the worker file a simple hello world, but still it fails.

When it was working in development the resource requested would be like http://localhost:1212/dist/0.dev.worker.js

But now after upgrading Webpack and Electron it looks like http://localhost:1212/dist/testOnly

This strikes me as probably a mistake, because the requested resource is of the name of the file we're spawning a worker from.

**Initializing our worker (pool)**
```js
import { Pool, Thread, Worker, spawn } from 'threads';
Pool(
    () =>
      spawn(new Worker('./testOnly'), {
        timeout: 30000,
      }),
    {
      size: 1,
      name: 'testOnly',
      concurrency: 10,
    }
  );
  ```

**testOnly.js**
```js
import { expose } from 'threads/worker';

expose({
  hello() {
    return 'world';
  },
});


```

**Comment by Nantris** [comment]
It occurred to me it might have been an issue due to `merge.smart` being removed from webpack, but after reconfiguring things I can say confidently that that's of no help either.

**Comment by andywer** [comment]
Hey @Slapbox!

Please share your webpack config, babel config (is used) and if you imported the `Worker` from `threads`. There are several things that might have an impact on this.

**Comment by Nantris** [comment]
Hey @andywer thanks for your reply!

I'm not sure I can share our webpack config in full since it's pretty extensive and spread across multiple files. I updated my code above slightly to show we are importing `Worker` from `threads` not from some other source.

**Our Babel config looks roughly like this:**

```js
const ignore = [
  "node_modules/",];
const presets = [
  ["@babel/preset-env", {
    "targets": { "electron": "11.2.0" },
    "useBuiltIns": "usage",
    "corejs": "3.6"
  }],
  "@babel/preset-react",
  "@babel/preset-flow",
];
const plugins = [
  "@emotion",
  "@babel/plugin-transform-flow-strip-types",
  "add-module-exports",
  "@babel/plugin-proposal-export-default-from",
  ["@babel/plugin-proposal-optional-chaining", { "loose": false }],
  "@babel/plugin-proposal-do-expressions",
  "@babel/plugin-proposal-export-namespace-from",
  "@babel/plugin-proposal-class-properties",
  "@babel/plugin-transform-classes",
  [
    "module-resolver", {
      "root": ["./"],
      "alias": {
        "@app": "./app/",
        "@desktop": "./app/desktop/",
        "@components": "./app/desktop/components/",
        "@containers": "./app/desktop/containers/",
        "@providers": "./app/desktop/providers/",
        "@main": "./app/desktop/main/",
      }
    }
  ],
];
```

**Our Webpack config looks roughly like this, (although there's a lot of additional stuff I've excluded):**

```js

export default {
  externals,
  context: rootPath,
  plugins: [
    new webpack.EnvironmentPlugin({
      NODE_ENV: 'production',
    }),
    new ThreadsPlugin({
      globalObject: 'self', // NOTE: 'self' is the default value, but we were getting the warning "your Webpack configuration has output.globalObject set to window"
      target: 'electron-node-worker',
    }),
    new HtmlWebpackPlugin({
      template: path.resolve(__dirname, '../app/desktop/index.html'),
      chunks: ['renderer'],
      filename: 'renderer.html',
    }),
    new CspHtmlWebpackPlugin(
  {
    'base-uri': ["'self'"],
    'object-src': ["'none'"],
    'script-src': ["'self' 'unsafe-eval'"],
    'style-src': ["'self' 'unsafe-inline'"],
    'frame-src': ["'none'"],
    // 'worker-src': ["'self'"], // @TODO -- Not sure what a working value is for this, and workers aren't working after upgrading to Webpack5 even without complicating things with CSP
  },
  {
    hashEnabled: {
      'script-src': true,
      'style-src': false,
    },
    nonceEnabled: {
      'script-src': true,
      'style-src': false,
    },
  }
),
  ],
  module: {
    rules: [
      {
        // loads .html files
        test: /\.(html)$/,
        include: [path.resolve(__dirname, 'app/desktop')],
        use: {
          loader: 'html-loader',
          options: {
            attributes: {
              list: [
                {
                  tag: 'img',
                  attribute: 'data-src',
                  type: 'src',
                },
              ],
            },
          },
        },
      },
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        include: [
          path.resolve(rootPath, 'app'),
          path.resolve(rootPath, 'packages'),
        ],
        use: {
          loader: 'babel-loader',
          options: {
            cacheDirectory: true,
            babelrc: true,
            plugins:
              process.env.NODE_ENV === 'development'
                ? [require.resolve('react-refresh/babel')].filter(Boolean)
                : [],
          },
        },
      },
    ],
  },
  output: {
    path: appFolderPath,
    libraryTarget: 'commonjs2',
  },
  resolve,
};
```

I already tried a number of changes to our configurations, but no luck.

**Comment by andywer** [comment]
Try adding the `"modules": false` setting as babel-preset-env option. I would guess that Babel transpiles the ES modules right now, rendering webpack and the threads-plugin unable to process imports/exports.

**Comment by Nantris** [comment]
Thanks for your reply @andywer. I just got a chance to give that a shot, but no dice.

I realized I forgot to mention we weren't previously using `html-webpack-plugin` either. 

I'd love to test without this plugin, but unfortunately our previous method of loading our app no longer works in Electron 9 and above so it's an all or nothing deal. Do you have any thoughts on whether that plugin may break the threads plugin or require some special considerations?

**Comment by Nantris** [comment]
The only thing that stands out as interesting in the webpack logging is:

```
WARNING in ./node_modules/threads/dist/master/implementation.node.js 43:8-34
Module not found: Error: Can't resolve 'ts-node' in 'C:\projects\myProject\node_modules\threads\dist\master'
```

**Comment by eranimo** [comment]
I'm pretty sure this plugin is not compatible at all with Webpack 5. I get the "no instantiations" message after upgrading, changing nothing else.

**Comment by Nantris** [comment]
@eranimo thanks for sharing your finding! That seems quite possible.

@andywer are you familiar with the changes to Webpack 5? Does anything stand out to you as a possible cause of the issue? https://webpack.js.org/blog/2020-10-10-webpack-5-release/#major-changes-removals

**Comment by andywer** [comment]
@Slapbox Are you using the latest version [1.4.0](https://github.com/andywer/threads-plugin/releases/tag/v1.4.0) of the plugin? That version is the first one supporting webpack 5.

**Comment by Nantris** [comment]
@andywer indeed we are. 

Let me know if anything comes to mind to investigate and I can try to provide more details about our setup.

**Comment by marekgregor** [comment]
I have found workaround: https://github.com/andywer/threads-plugin/issues/34#issuecomment-779343515
hopefully it helps.

**Comment by Nantris** [comment]
@marekgregor thanks for sharing. Unfortunately for us (not using TypeScript) that leads Webpack to never complete the build, slowly accumulating more system memory but never finishing the build.

**Comment by Nantris** [comment]
Revisiting this, I found that if I set the following content security policy, I get this error:


```js
new CspHtmlWebpackPlugin(
  {
    'base-uri': ["'self'"],
    'object-src': ["'none'"],
    'script-src': ["'self' 'unsafe-eval'"],
    'style-src': ["'self' 'unsafe-inline'"],
    'frame-src': ["'none'"],
    'worker-src': ["'*'"],
  },
  {
    hashEnabled: {
      'script-src': false,
      'style-src': false,
    },
    nonceEnabled: {
      'script-src': false,
      'style-src': false,
    },
  }
),
```

```
react_devtools_backend.js:2430 DOMException: Failed to construct 'Worker': Access to the script at 'http://localhost/dist/myWorker' is denied by the document's Content Security Policy.
    at new WebWorker (webpack-internal:///./node_modules/threads/dist/master/implementation.browser.js:38:13)
    at pool.size (webpack-internal:///./packages/shared/utils/src/createMarkup.js:36:109)
    at eval (webpack-internal:///./node_modules/threads/dist/master/pool.js:43:15)
    at Array.map (<anonymous>)
    at spawnWorkers (webpack-internal:///./node_modules/threads/dist/master/pool.js:42:31)
    at new WorkerPool (webpack-internal:///./node_modules/threads/dist/master/pool.js:60:24)
    at PoolConstructor (webpack-internal:///./node_modules/threads/dist/master/pool.js:284:12)
    at createWorkerPool (webpack-internal:///./packages/shared/utils/src/createMarkup.js:36:55)
```

----

Strangely if I remove the content security policy, instead I get a network error.

![image](https://user-images.githubusercontent.com/6835891/108763562-7dcdb000-751f-11eb-8bfd-6977e965a30a.png)


and indeed, checking `http://localhost/webpack-dev-server` the worker file is not in the output.

@andywer does any of this possibly help?

**Comment by Nantris** [comment]
Possibly the same issue? https://github.com/andywer/threads-plugin/issues/32#issue-754614480

I've spent all day so far researching and troubleshooting but I'm not any closer to resolution. 

I think we're going to be stuck on this until someone else, hopefully, has an idea for something we can give a try or an avenue we can research.

We tried gutting our worker code and just using `expose` to expose the simplest method that returns a string, but the outcome is the same so I don't think it's related to the worker file's code. 

It seems like this line or the surrounding code isn't running based on the findings in my initial post
https://github.com/andywer/threads-plugin/blob/master/src/loader.js#L46

> When it was working in development the resource requested would be like http://localhost:1212/dist/0.dev.worker.js

> But now after upgrading Webpack and Electron it looks like http://localhost:1212/dist/testOnly

Specifically that's the URI of the requested resource - but there's nothing at that address or output to the filesystem.

**Comment by Nantris** [comment]
Also tried using the `plugins` key in vain. Didn't think it would have the desired effect, but when you're out of things to try...

```js
    new ThreadsPlugin({
      globalObject: 'self',
      target: 'electron-node-worker',
      plugins: [
        'HtmlWebpackPlugin',
      ],
    })
```

**Comment by Nantris** [comment]
Also tried removing `sideEffects: false` from our package which contains the worker.

**Comment by Nantris** [comment]
Resolved by removing threads-plugin in favor of creating workers in line with this example: https://github.com/webpack/webpack/tree/master/examples/worker

and then wrapping the created worker with `spawn` from threads.js just like before.

If anyone gets stuck on this ping me and I'll try to give you pointers to get it working.


```js
spawn(
  new Worker(new URL('./heavyLifterWorker', import.meta.url), {
    name: 'heavyLifter',
  }),
  { timeout: 30000 }
),
```

**Comment by andywer** [comment]
@Slapbox You already did it? Nice! 🥳

**Comment by stephencorwin** [comment]
I am still getting an error with the proposed fix:
```ts
// TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. 
// Received an instance of URL
const pool = Pool(async () => {
  const worker = await spawn(new Worker(new URL('./worker', import.meta.url)));
  return worker;
});
```
using `.href` or `.pathname` or `.toString()` on the created URL does not seem to work either.

**Comment by Nantris** [comment]
@stephencorwin do you need `async/await`? It's working fine without for us - though it's extremely unlikely that's your issue.

What's your environment? We're using Electron, and I've found that the `URL` constructor seems to have slight differences in Node versus the browser.

I'm not sure, but you may need the second argument to `new Worker` where you put the name of the worker, like,

```js
{
  name: 'heavyLifter',
}
```

Let me know if any of that helps - or if it doesn't.

**Comment by stephencorwin** [comment]
I do need the async/await. I removed my additional code to keep it simple, but I am calling an exposed function after the worker has spawned within the Pool closure.
```ts
const pool = Pool(async () => {
  const worker = await spawn(new Worker(new URL('./worker', import.meta.url)));
  await worker.setContext(context); // <-- this line here
  return worker;
});
```
The error happens regardless of if I remove the async/await though. I also tried both anonymous and named workers like you suggested.
  
I am running this within a node environment. Is the a proper substitute for `URL` within Node? @Slapbox

**Comment by Nantris** [comment]
Hm... What version of Node are you running? We're on 12.18.x. But I'm not sure if we're using the actual node `URL` constructor now that I'm thinking about it.

----

I doubt this will work, but you can try:

`import { URL } from 'url-polyfill'`

and add the following line to your `package.json`

`"url-polyfill": "defunctzombie/node-url"`

-----


Or, can you try constructing the URL outside of the `Pool()` function and then passing the resulting string to the `Worker` constructor?

**Comment by stephencorwin** [comment]
I tried both node v12.18 as well as upgrading to v14.16. Same deal :(
Pollyfill doesn't seem to help. Nor does constructing the url outside of the pool. I actually get the same error constructing it either inside or outside.
```bash
WARNING in ./node_modules/threads/dist/master/implementation.node.js 84:10-99 
Critical dependency: the request of a dependency is an expression
```
Not sure if this is new or not though tbh. I definitely didn't notice it before, but that might be because I was used to seeing the `0 instances warning`.

**Comment by Nantris** [comment]
Agh I'm not really sure, maybe @andywer has some idea.

I doubt that the warning is causing you any trouble, I see those seemingly all the time.

Just to be sure, you're still (correctly) using `import { Worker } from 'threads'`, right? Not from `child_process`?

Is your Webpack fully up to date?

**Comment by stephencorwin** [comment]
Not sure if you are on Discord @Slapbox, but I would be happy to share my screen if you wouldn't mind further investigation. (I'll report back the fix here if it is discovered)

My Discord username is ScoreWin#2381

**Comment by stephencorwin** [comment]
And yea, my webpack is fully up-to-date. Everything was working great on webpack v4 and I started running into this issue after I got the build working again in webpack v5. A little googling and here I am 😄

**Comment by andywer** [comment]
Yes, the `Critical dependency: the request of a dependency is an expression` is a bit ugly, but I don't think there is any actual harm done. Not sure yet how to get around this warning yet, though.

Still need to update the docs for webpack 5…

**Comment by stephencorwin** [comment]
Okay, so I made some progress. After some inspection, I found that the url that was generated was not quite correct using the above listed method.
```ts
// This doesn't work at all for me. Invalid arg error
await spawn(new Worker(new URL('./worker', import.meta.url)))

// This would try to find the module and get this error:
// Error: Cannot find module 'D:\scorewin\projects\letsgoraiding\letsgoraiding-game\.webpack.build\server.dev\file:\D:\scorewin\projects\letsgoraiding\letsgoraiding-game\.webpack.build\server.dev\8d50f104187e4c75891d.ts'
await spawn(new Worker(new URL('./worker', import.meta.url).href))
```
After some massaging:
```ts
const workerURL = `./${new URL('./worker', import.meta.url).href.replace(/^.*[\\\/]/,'')}`;
await spawn(new Worker(workerURL))
```
This correctly finds the module and attempts to load it, but then errors out because it isn't transpiled into JS from TS. This seems to be one part of the functionality that the ThreadsPlugin was providing before and is lost in this new approach... at least with TS.

@andywer I don't think we are at the point where the docs can be safely updated to instruct folks that the ThreadsPlugin isn't needed for Webpack v5. We're pretty close -- but for TypeScript users, this will definitely pose an issue. Not to mention, the cleanliness of the import is pretty much lost compared to previous versions. Perhaps some abstraction sugar is worth investigating once we get this working again.

If you would like, I can open a new issue, but my issue seems directly related to this issue. The main difference is that @Slapbox is within an Electron env instead of Node and they are using JS instead of TS.

**Comment by stephencorwin** [comment]
If I use the threads-plugin loader directly, it seems to transpile, but there are still some module resolution issues:
```ts
// TypeError [Error]: (0 , threads__WEBPACK_IMPORTED_MODULE_15__.isWorkerRuntime) is not a function
//  at D:\scorewin\projects\letsgoraiding\letsgoraiding-game\.webpack.build\server.dev\worker.worker.js:55791:62
import workerURL from 'threads-plugin/dist/loader?name=worker!./worker.ts';
await spawn(new Worker(`./${workerURL}`))
console.log(workerURL); // -> "worker.worker.js"

// within worker.ts
// this is needed otherwise I get "Error: expose() called in the master thread."
if (isWorkerRuntime()) {
  expose({
    setContext,
    plan,
    prune,
    postProcess,
    cleanup,
    getSets,
    getPermutations,
  });
}
```

**Comment by Nantris** [comment]
@stephencorwin awesome progress! I had already hit the end of my usefulness last night and I'm glad to see you've been able to make headway on the issue.

Maybe post a question on StackExchange about how to get Webpack to transpile TS for workers and link it here so we can upvote? I think that the threads-plugin is on the way out with Webpack 5 having native support for this, even if it's still got some issues.

I wonder also if you could use the inline loader syntax to get it to transpile your TS code? I'm spitballing though, I don't use TS.

**Comment by lucaju** [comment]
Any news on this issue? @andywer?

I used Thread.js for 3 month without any problems. As soon as I updated to Webpack 5, things went south.
I tried every solution proposed here... no luck.

Like @stephencorwin, I am working with TS, compiling with webpack + babel. But I am targeting the browser.

By the way, this is an amazing project @andywer. Thank you so much.

**Comment by stephencorwin** [comment]
@lucaju I ended up not being able to figure this out and reverted to Webpack 4. I was a bit disappointed, but support just wasn't quite there for Webpack 5 + TS + Threads.js

**Comment by andywer** [comment]
Sorry, folks! Webpack 5 is definitely a priority for the project, it's just that I couldn't dedicate much of my time recently and we are a bit short on contributors and sponsors here.

I am still a bit sick, but I will see if I can find some time this weekend to look into this.

**Comment by linonetwo** [comment]
Wish you have a good health @andywer , we all should have WLB when doing opensource.

Actually, I think everyone here is doing opensource, because if someone uses this threads-plugin in his company commercially, he will have enough working hour to help upgrade it.

**Comment by lucaju** [comment]
I also ended up going back to Webpack 4, but also because of another dependency.

Yep, I'm also doing Open Source projects. This one in particular is a XML semantic editor. I am using Thread.js to facilitate communication with web worker to perform XML validation. In my case, I am developing the webworker in a different repository, so, potentially, it could use its own webpack setup to transpile the code and copy to the main repo that consumes the webworker. Not sure if it would work. I will try this next time.

I hope you get better soon @andywer.

**Comment by CSharperMantle** [comment]
Keeping an eye on this issue. Anyway @andywer you have done an awesome job in unifying the Worker interface!

**Comment by andrec93p** [comment]
Dropping this here in case it helps anybody.

With Electron specifically (Electron 22, Webpack 5, `threads` 1.7.0, `threads-plugin` 1.4.0, TypeScript, macOS), I was trying using @stephencorwin's solution to no avail. 

I was convinced the worker files were not being transpiled; turns out they _were_, but they were not handle correctly in the `.asar` archive. I had to put an additional option in the `package.json` file so they were included in the package.

So to recap (I hope I'm not forgetting anything):
- `threads-plugin` installed as a devDepedency.
- Webpack set up like this.
```
const configuration: webpack.Configuration = {
  ...
  plugins: [
    ...
    new ThreadsPlugin({target: 'electron-node-worker'}),
  ],
  ...
};
```
- Regular worker script with the `expose` function.
- Workers imported and instantiated like this (may require a couple of `// @ts-ignore`s).
```
import myWorkerUrl from "threads-plugin/dist/loader?name=myWorker!../workers/myWorker";

// ...

spawn<MyWorkerType>(
  new Worker(`./${myWorkerUrl}`),
))
```
- And **this** in `package.json` (the part I was missing) (credits to [this electron issue](https://github.com/electron-userland/electron-builder/issues/1841)).
```
{
   ...
   "build": {
      ...
      "asar": true,
      "asarUnpack": ["**\\*.{node,dll}", "./dist/main/*.worker.js"],
      ...
   }
}
```

No need for anything `"type": "module"` in `package.json`, `"module": "esnext"` in `tsconfig.json` or `nodeIntegrationInWorker` for the `BrowserWindow`.
