### ISSUE TITLE
Does not work with require

### ISSUE THREAD

**Issue by AllanOricil** [andywer/threads-plugin#40]
For some reason when I change from import to require, I get this warning and the worker file is not emitted in my dist. If I use import, then my code breaks, but the file is emitted. How can I fix it?

![image](https://user-images.githubusercontent.com/55927613/115956430-837e4c80-a4f4-11eb-89f9-4ca660738893.png)

When using Import

![image](https://user-images.githubusercontent.com/55927613/115956535-3b135e80-a4f5-11eb-9dee-f4b6f20b7220.png)

**Comment by andywer** [comment]
Hey @AllanOricil. Yeah, this is as intended. There is unfortunately no easy way around that right now.

Background: ES imports/exports are easy to parse, `require()` call assignments are not. Especially when Babel compiles it, it produces a bit of a hard-to-trace-back mess in the code.

**Comment by AllanOricil** [comment]
@andywer ok. It is better if you add on the README "It does not work with common js (require)"
